name: phdthesis
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.11.16=py310hc74094e_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - aom=3.7.1=h463b476_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - blosc=1.21.5=h9c252e8_1
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.1.0=py310hb4ad77e_2
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.4=h5505292_0
  - ca-certificates=2025.1.31=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=hd1e100b_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py310h497396d_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - contourpy=1.3.1=py310h7f4e7e6_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hb547adb_0
  - double-conversion=3.3.1=h286801f_0
  - eigen=3.4.0=h1995070_0
  - expat=2.5.0=hb7217d7_1
  - fenics-basix=0.6.0=py310ha2eaeab_5
  - fenics-basix-pybind11-abi=0.4.15=h9fc730b_5
  - fenics-dolfinx=0.6.0=py310h5dd6fb5_109
  - fenics-ffcx=0.6.0=pyh56297ac_0
  - fenics-libbasix=0.6.0=hdc94a70_5
  - fenics-libdolfinx=0.6.0=h53d26b6_109
  - fenics-ufcx=0.6.0=h56297ac_0
  - fenics-ufl=2023.1.1=pyhd8ed1ab_1
  - ffmpeg=6.1.1=gpl_h4d3b11e_100
  - fftw=3.3.10=mpi_openmpi_haef8dc3_9
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.57.0=py310hc74094e_0
  - freetype=2.12.1=hadb7bae_2
  - fribidi=1.0.10=h27ca646_0
  - frozenlist=1.5.0=py310hc74094e_1
  - gettext=0.23.1=h3dcc1bd_0
  - gettext-tools=0.23.1=h493aca8_0
  - gl2ps=1.4.2=h17b34a0_0
  - glew=2.1.0=h9f76cd9_2
  - glib=2.80.2=h535f939_0
  - glib-tools=2.80.2=h4c882b9_0
  - gmp=6.3.0=h7bae524_2
  - gnutls=3.7.9=hd26332c_0
  - graphite2=1.3.13=hebf3989_1003
  - gst-plugins-base=1.24.4=h8a8f8c8_0
  - gstreamer=1.24.4=h430e707_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py310h8ca6390_100
  - harfbuzz=8.5.0=h1836168_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.3=mpi_openmpi_h7d685e0_4
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - hypre=2.28.0=mpi_openmpi_haba3941_0
  - icu=73.2=hc8870d7_0
  - idna=3.10=pyhd8ed1ab_1
  - jsoncpp=1.9.5=hc021e02_1
  - kahip=3.15=h0d8eabd_2
  - kahip-python=3.15=py310hc8667b9_2
  - kiwisolver=1.4.7=py310h7306fd8_0
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libadios2=2.9.1=mpi_openmpi_h3fe9733_4
  - libaec=1.1.3=hebf3989_0
  - libasprintf=0.23.1=h493aca8_0
  - libasprintf-devel=0.23.1=h493aca8_0
  - libass=0.17.1=hf7da4fe_1
  - libblas=3.9.0=31_h10e41b3_openblas
  - libboost=1.82.0=h72cdd8a_6
  - libboost-devel=1.82.0=hf450f58_6
  - libboost-headers=1.82.0=hce30654_6
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libclang-cpp15=15.0.7=default_he012953_5
  - libclang13=18.1.7=default_hb9c8b4a_0
  - libcurl=8.8.0=h7b6f9a7_1
  - libcxx=20.1.2=ha82da77_0
  - libdeflate=1.20=h93a5062_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.6=h1da3d7d_1
  - libgettextpo=0.23.1=h493aca8_0
  - libgettextpo-devel=0.23.1=h493aca8_0
  - libgfortran=5.0.0=14_2_0_h6c33f7e_2
  - libgfortran5=14.2.0=h6c33f7e_2
  - libglib=2.80.2=h535f939_0
  - libhwloc=2.11.2=default_h3f80f97_1000
  - libiconv=1.18=hfe07756_1
  - libidn2=2.3.8=h38aa460_0
  - libintl=0.23.1=h493aca8_0
  - libintl-devel=0.23.1=h493aca8_0
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - libllvm15=15.0.7=h2621b3d_4
  - libllvm18=18.1.7=hdac5640_0
  - liblzma=5.8.1=h39f12f2_0
  - liblzma-devel=5.8.1=h39f12f2_0
  - libnetcdf=4.9.2=nompi_he469be0_114
  - libnghttp2=1.58.0=ha4dd798_1
  - libogg=1.3.5=h99b78c6_0
  - libopenblas=0.3.29=openmp_hf332438_0
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.43=h091b4b1_0
  - libpq=16.8=ha7343d6_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtasn1=4.20.0=h5505292_0
  - libtheora=1.1.1=h99b78c6_1006
  - libtiff=4.6.0=h07db509_3
  - libunistring=0.9.10=h3422bc3_0
  - libvorbis=1.3.7=h9f76cd9_0
  - libvpx=1.13.1=hb765f3a_0
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.12.7=ha661575_1
  - libzip=1.10.1=ha0bc3c6_3
  - libzlib=1.2.13=hfb2fe0b_6
  - llvm-openmp=20.1.2=hdb05f8b_0
  - loguru=0.7.2=py310hbe9552e_2
  - lz4-c=1.9.4=hb7217d7_0
  - matplotlib=3.10.1=py310hb6292c7_0
  - matplotlib-base=3.10.1=py310hadbac3a_0
  - metis=5.1.0=h15f6cfe_1007
  - mpfr=4.2.1=hb693164_3
  - mpi=1.0=openmpi
  - mpi4py=3.1.6=py310hd3bd7df_0
  - msgpack-python=1.1.0=py310h7306fd8_0
  - multidict=6.3.2=py310hdf261b0_0
  - mumps-include=5.2.1=hce30654_11
  - mumps-mpi=5.2.1=h51c74a9_11
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.3.0=hd1853d3_4
  - mysql-libs=8.3.0=hf036fc4_4
  - ncurses=6.5=h5e97a16_3
  - nettle=3.9.1=h40ed0f5_0
  - nlohmann_json=3.11.3=h00cdb27_1
  - nspr=4.36=h5833ebf_0
  - nss=3.100=hc6e9f88_0
  - numpy=1.26.4=py310hd45542a_0
  - openh264=2.4.0=h965bd2d_0
  - openjpeg=2.5.2=h9f1df11_0
  - openmpi=4.1.6=h526c993_101
  - openssl=3.4.1=h81ee809_0
  - p11-kit=0.24.1=h29577a5_0
  - packaging=24.2=pyhd8ed1ab_2
  - parmetis=4.0.3=h6eb5794_1005
  - pcre2=10.43=h26f9a81_0
  - petsc=3.19.6=real_h0603ae5_100
  - petsc4py=3.19.6=real_h934ce05_100
  - pillow=10.3.0=py310h81a8c2e_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=h2f9eb0b_0
  - pkg-config=0.29.2=hab62308_1008
  - platformdirs=4.3.7=pyh29332c3_0
  - pooch=1.8.2=pyhd8ed1ab_1
  - proj=9.3.0=h52fb9d0_2
  - propcache=0.2.1=py310hc74094e_1
  - pthread-stubs=0.4=hd74edd7_1002
  - ptscotch=6.0.9=h1aec651_2
  - pugixml=1.13=h13dd4ca_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.14=h2469fbe_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=6_cp310
  - pyvista=0.44.2=pyhd8ed1ab_1
  - qhull=2020.2=h420ef59_5
  - qt-main=5.15.8=hf679f28_21
  - readline=8.2=h1d1bf99_2
  - requests=2.32.3=pyhd8ed1ab_1
  - scalapack=2.2.0=h515df86_1
  - scipy=1.15.2=py310h32ab4ed_0
  - scooby=0.10.0=pyhd8ed1ab_1
  - scotch=6.0.9=h7537618_2
  - six=1.17.0=pyhd8ed1ab_0
  - slepc=3.19.2=real_h63bf394_100
  - slepc4py=3.19.2=real_h1824401_101
  - snappy=1.2.1=h98b9ce2_1
  - sqlite=3.46.0=h5838104_0
  - suitesparse=5.10.1=h79486c6_3
  - superlu=7.0.0=h742a510_1
  - superlu_dist=7.2.0=hfdb8677_0
  - svt-av1=1.8.0=h463b476_0
  - tbb=2022.1.0=h9541205_0
  - tbb-devel=2022.1.0=hf29b1df_0
  - tk=8.6.13=h5083fa2_1
  - tornado=6.4.2=py310h078409c_0
  - typing-extensions=4.13.1=hf5ce1d7_0
  - typing_extensions=4.13.1=pyh29332c3_0
  - unicodedata2=16.0.0=py310h078409c_0
  - urllib3=2.3.0=pyhd8ed1ab_0
  - utfcpp=4.0.6=h54c0426_0
  - vtk=9.2.6=qt_py310h1234567_218
  - vtk-base=9.2.6=qt_py310h1234567_218
  - vtk-io-ffmpeg=9.2.6=qt_py310h1234567_218
  - wheel=0.45.1=pyhd8ed1ab_1
  - wslink=2.3.3=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.8.1=h9a6d368_0
  - xz-gpl-tools=5.8.1=h9a6d368_0
  - xz-tools=5.8.1=h39f12f2_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.18.3=py310hc74094e_1
  - zeromq=4.3.5=hc1bb282_7
  - zfp=0.5.5=hcfdfaf5_8
  - zlib=1.2.13=hfb2fe0b_6
  - zstandard=0.23.0=py310h078409c_1
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - appnope==0.1.4
      - asttokens==3.0.0
      - cftime==1.6.4.post1
      - comm==0.2.2
      - debugpy==1.8.13
      - decorator==5.2.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fluidfoam==0.2.9
      - gmsh==4.13.1
      - gmsh-api==4.13.0
      - ipykernel==6.29.5
      - ipython==8.34.0
      - jedi==0.19.2
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - matplotlib-inline==0.1.7
      - nest-asyncio==1.6.0
      - netcdf4==1.7.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyforce==0.1.3
      - pygments==2.19.1
      - pytz==2025.2
      - pyzmq==26.4.0
      - scikit-learn==1.6.1
      - setuptools==63.0.0
      - stack-data==0.6.3
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - tzdata==2025.2
      - wcwidth==0.2.13
prefix: /Users/sriva/miniconda3/envs/phdthesis
